notifications:
    commits:      commits@sedona.apache.org
    issues_status:       issues@sedona.apache.org
    pullrequests_status:  dev@sedona.apache.org
    jira_options: link label comment
github:
  description: "A cluster computing framework for processing large-scale geospatial data"
  homepage: http://sedona.apache.org/
  labels:
    - geospatial
    - cluster-computing
    - spatial-query
    - spatial-analysis
    - spatial-sql
    - scala
    - java
    - python
  features:
    # Enable wiki for documentation
    wiki: false
    # Enable issue management
    issues: false
    # Enable projects for project management boards
    projects: false
  ghp_branch:
